name: Update Mirror
on:
  push:
    branches: 'amazing'
#   schedule:
#     - cron: '1 1 * * 6'
#     - cron: "1 20 * * *"

jobs:
  mirror-from-savannah:
    runs-on: ubuntu-latest
    steps:
      - run: |
          rm -rf acl.git || true
          git clone --mirror "https://git.savannah.nongnu.org/git/acl.git"
          cd acl.git
          git fetch -p origin
          git push --mirror
          rm -rf acl.git
      
